<a href="https://colab.research.google.com/github/merajsiddieque/ML-Lab/blob/main/ML_Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

In [ ]:
# Encode target
le = LabelEncoder()
df['Species_encoded'] = le.fit_transform(df['Species'])

In [ ]:
X = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = df['Species_encoded']


In [ ]:
# Train, validation, test split
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

In [ ]:
X_train2, X_temp2, y_train2, y_temp2 = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
X_val2, X_test2, y_val2, y_test2 = train_test_split(X_temp2, y_temp2, test_size=0.5, random_state=42, stratify=y_temp2)

In [ ]:
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(120, 4)
(15, 4)
(15, 4)


In [ ]:
df_0 = df[df['Species_encoded'] == 0]
df_1 = df[df['Species_encoded'] == 1]
df_2 = df[df['Species_encoded'] == 2]

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_val_s   = scaler.transform(X_val)
X_test_s  = scaler.transform(X_test)

model = LinearRegression()
model.fit(X_train_s, y_train)

LinearRegression()

In [ ]:
scaler = StandardScaler()
X_train2_s = scaler.fit_transform(X_train2)
X_val2_s   = scaler.transform(X_val2)
X_test2_s  = scaler.transform(X_test2)

model2 = LinearRegression()
model2.fit(X_train2_s, y_train2)

LinearRegression()

In [ ]:
def predict_classes(X_scaled):
    preds = model.predict(X_scaled)
    preds_round = np.rint(preds).astype(int)  # round to nearest integer
    preds_round = np.clip(preds_round, y.min(), y.max())  # keep 0,1,2 only
    return preds_round

y_pred_test = predict_classes(X_test_s)

In [ ]:
def predict_classes(X_scaled):
    preds = model.predict(X_scaled)
    preds_round = np.rint(preds).astype(int)  # round to nearest integer
    preds_round = np.clip(preds_round, y.min(), y.max())  # keep 0,1,2 only
    return preds_round

y_pred_test2 = predict_classes(X_test2_s)

In [ ]:
print(y_pred_test)

[0 1 2 0 2 2 1 1 2 0 0 2 1 0 1]


In [ ]:
print(y_pred_test2)

[0 0 2 1 2 2 1 2 0 1 1 0 1 2 1 2 0 1 2 0 1 2 0]


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Test Accuracy:", accuracy_score(y_test, y_pred_test))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_test))
print("\nClassification Report:\n", classification_report(y_test, y_pred_test, target_names=le.classes_))

Test Accuracy: 1.0

Confusion Matrix:
 [[5 0 0]
 [0 5 0]
 [0 0 5]]

Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         5
Iris-versicolor       1.00      1.00      1.00         5
 Iris-virginica       1.00      1.00      1.00         5

       accuracy                           1.00        15
      macro avg       1.00      1.00      1.00        15
   weighted avg       1.00      1.00      1.00        15



In [ ]:
print("Test Accuracy:", accuracy_score(y_test2, y_pred_test2))
print("\nConfusion Matrix:\n", confusion_matrix(y_test2, y_pred_test2))
print("\nClassification Report:\n", classification_report(y_test2, y_pred_test2, target_names=le.classes_))

Test Accuracy: 1.0

Confusion Matrix:
 [[7 0 0]
 [0 8 0]
 [0 0 8]]

Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       1.00      1.00      1.00         8
 Iris-virginica       1.00      1.00      1.00         8

       accuracy                           1.00        23
      macro avg       1.00      1.00      1.00        23
   weighted avg       1.00      1.00      1.00        23



In [ ]:
# Downsample Setosa to only 10 samples
minority_class = 0   #-->Setosa,  1-->Versicolor, 2--> Virginica
idx_min = np.where(y == minority_class)[0]
idx_maj = np.where(y != minority_class)[0]

np.random.seed(42)
keep_idx = np.random.choice(idx_min, size=10, replace=False)
new_idx = np.concatenate([keep_idx, idx_maj])

X_imb = X.iloc[new_idx].reset_index(drop=True)
y_imb = y.iloc[new_idx].reset_index(drop=True)

y_imb.value_counts()


Species_encoded
1    50
2    50
0    10
Name: count, dtype: int64

In [ ]:
# 80:10:10 split
X_train, X_temp, y_train, y_temp = train_test_split(
    X_imb, y_imb, test_size=0.2, stratify=y_imb, random_state=42
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42
)

print("Before oversampling:", pd.Series(y_train).value_counts())


Before oversampling: Species_encoded
1    40
2    40
0     8
Name: count, dtype: int64


In [ ]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=42)
X_res, y_res = ros.fit_resample(X_train, y_train)

print("After oversampling:", pd.Series(y_res).value_counts())


After oversampling: Species_encoded
1    40
2    40
0    40
Name: count, dtype: int64


In [ ]:
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_res)
X_val_s   = scaler.transform(X_val)
X_test_s  = scaler.transform(X_test)

model = LinearRegression()
model.fit(X_train_s, y_res)

# Predict
y_pred = model.predict(X_test_s)
y_pred = np.rint(y_pred).astype(int)
y_pred = np.clip(y_pred, y.min(), y.max())

print("Prediction: ", y_pred)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=le.classes_))


Prediction:  [1 1 1 2 0 2 2 1 1 1 2]
Accuracy: 0.9090909090909091
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         1
Iris-versicolor       0.83      1.00      0.91         5
 Iris-virginica       1.00      0.80      0.89         5

       accuracy                           0.91        11
      macro avg       0.94      0.93      0.93        11
   weighted avg       0.92      0.91      0.91        11



#3


In [ ]:
from imblearn.over_sampling import SMOTE
# Artificially make Setosa (class 0) minority
minority_class = 0   #--> Setosa,  1-->Versicolor, 2--> Virginica
idx_min = np.where(y == minority_class)[0]
idx_maj = np.where(y != minority_class)[0]

np.random.seed(42)
keep_idx = np.random.choice(idx_min, size=10, replace=False)
new_idx = np.concatenate([keep_idx, idx_maj])

X_imb = X.iloc[new_idx].reset_index(drop=True)
y_imb = y.iloc[new_idx].reset_index(drop=True)

y_imb.value_counts()


Species_encoded
1    50
2    50
0    10
Name: count, dtype: int64

In [ ]:
# 80:10:10 split
X_train, X_temp, y_train, y_temp = train_test_split(
    X_imb, y_imb, test_size=0.2, stratify=y_imb, random_state=42
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42
)

print("Before SMOTE:", pd.Series(y_train).value_counts())


Before SMOTE: Species_encoded
1    40
2    40
0     8
Name: count, dtype: int64


In [ ]:
# SMOTE with k_neighbors=2 (take any 2 samples from minority class)
smote_a = SMOTE(random_state=42, k_neighbors=2)
X_res_a, y_res_a = smote_a.fit_resample(X_train, y_train)

print("After SMOTE (k=2):", pd.Series(y_res_a).value_counts())


After SMOTE (k=2): Species_encoded
1    40
2    40
0    40
Name: count, dtype: int64


In [ ]:
scaler = StandardScaler()
X_train_a = scaler.fit_transform(X_res_a)
X_val_a   = scaler.transform(X_val)
X_test_a  = scaler.transform(X_test)

model_a = LinearRegression()
model_a.fit(X_train_a, y_res_a)

y_pred_a = model_a.predict(X_test_a)
y_pred_a = np.rint(y_pred_a).astype(int)
y_pred_a = np.clip(y_pred_a, y.min(), y.max())

print("Performance with SMOTE (k=2):")
print("Accuracy:", accuracy_score(y_test, y_pred_a))
print(classification_report(y_test, y_pred_a, target_names=le.classes_))


Performance with SMOTE (k=2):
Accuracy: 0.9090909090909091
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         1
Iris-versicolor       0.83      1.00      0.91         5
 Iris-virginica       1.00      0.80      0.89         5

       accuracy                           0.91        11
      macro avg       0.94      0.93      0.93        11
   weighted avg       0.92      0.91      0.91        11



In [ ]:
# SMOTE with nearest neighbor (default k=5)
smote_b = SMOTE(random_state=42, k_neighbors=5)
X_res_b, y_res_b = smote_b.fit_resample(X_train, y_train)

print("After SMOTE (nearest neighbors, k=5):", pd.Series(y_res_b).value_counts())


After SMOTE (nearest neighbors, k=5): Species_encoded
1    40
2    40
0    40
Name: count, dtype: int64


In [ ]:
scaler = StandardScaler()
X_train_b = scaler.fit_transform(X_res_b)
X_val_b   = scaler.transform(X_val)
X_test_b  = scaler.transform(X_test)

model_b = LinearRegression()
model_b.fit(X_train_b, y_res_b)

y_pred_b = model_b.predict(X_test_b)
y_pred_b = np.rint(y_pred_b).astype(int)
y_pred_b = np.clip(y_pred_b, y.min(), y.max())

print("Performance with SMOTE (k=5):")
print("Accuracy:", accuracy_score(y_test, y_pred_b))
print(classification_report(y_test, y_pred_b, target_names=le.classes_))


Performance with SMOTE (k=5):
Accuracy: 0.9090909090909091
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         1
Iris-versicolor       0.83      1.00      0.91         5
 Iris-virginica       1.00      0.80      0.89         5

       accuracy                           0.91        11
      macro avg       0.94      0.93      0.93        11
   weighted avg       0.92      0.91      0.91        11

